# Generated by Django 3.0.6 on 2020-05-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
