# Generated by Django 3.0.6 on 2020-05-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rate_increase',
            field=models.IntegerField(default=0.1),
        ),
    ]
