# Generated by Django 3.0.6 on 2020-05-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200520_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rate_increase',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=2),
        ),
    ]
