# Generated by Django 3.0.6 on 2020-05-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shipments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipments',
            new_name='Shipment',
        ),
    ]
