# Generated by Django 3.0.6 on 2020-05-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200521_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='company_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='company_name',
            field=models.ForeignKey(default='python', on_delete=django.db.models.deletion.CASCADE, to='accounts.Company', to_field='company_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
