# Generated by Django 3.0.6 on 2020-05-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200521_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
