# Generated by Django 3.0.6 on 2020-05-23 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_remove_shipment_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='company_name',
            field=models.ForeignKey(default='cool', on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
