# Generated by Django 3.0.6 on 2020-05-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='invoice_number',
            new_name='tracking_number',
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='ref_1',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='ref_2',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_level',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.IntegerField(default='123'),
            preserve_default=False,
        ),
    ]
