# Generated by Django 3.0.6 on 2020-06-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rate_increase',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('shipment_date', models.DateTimeField()),
                ('service_level', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('ref_1', models.CharField(max_length=20)),
                ('ref_2', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyname', to='accounts.Company', to_field='user')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
