# Generated by Django 3.0.6 on 2020-05-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200521_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.Company', to_field='company_name'),
        ),
    ]
