# Generated by Django 3.0.6 on 2020-05-21 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
