# Generated by Django 3.0.6 on 2020-05-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_shipment_shipment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='company_name',
        ),
    ]
