# Generated by Django 3.0.6 on 2020-05-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200522_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
