# Generated by Django 3.0.6 on 2020-05-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_shipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
